### ISSUE TITLE
demo: How do I increase the capacity of the demo environment

### ISSUE THREAD

**Issue by aglitke** [ceph/ceph-container#1050]
Hi!  I am creating a ceph demo environment in k8s and want to use more space than the default 10G.  I've looked through the code and am unable to figure out how/if this is possible. Can anyone provide some guidance?  Thanks in advance!

```
  - args:
    - demo
    env:
    - name: MON_IP
      value: 192.168.122.96
    - name: CEPH_PUBLIC_NETWORK
      value: 0.0.0.0/0
    - name: RGW_CIVETWEB_PORT
      value: "81"
    - name: CEPH_DEMO_UID
      value: demo
    image: ceph/daemon:v3.0.3-stable-3.0-luminous-centos-7-x86_64
    imagePullPolicy: IfNotPresent
    name: ceph
    ports:
    - containerPort: 6789
      hostPort: 6789
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/ceph
      name: cephvarlib
    - mountPath: /etc/ceph
      name: cephetc
```
