### ISSUE TITLE
ceph/demo missing from hub.docker.com

### ISSUE THREAD

**Issue by majgis** [ceph/ceph-container#1250]
Is this a bug report or feature request?
Bug Report

What happened:
Revisiting an older build, this docker-compose entry no longer works:
```
  ceph:
    image: ceph/demo:tag-build-master-hammer-centos-7
    ports:
      - "7047:8080"
    volumes:
      - "ceph-config:/var/lib/ceph"
      - "ceph-data:/etc/ceph"
```

What you expected to happen:
A reproducible build

How to reproduce it (minimal and precise):
```
docker pull ceph/demo:tag-build-master-hammer-centos-7
```
Are there details on this transition somewhere?
Can I slide in another image and it will work or additional changes to consider?
