### ISSUE TITLE
Regarding SKYDNS Resolution

### ISSUE THREAD

**Issue by kannanvr** [ceph/ceph-container#1360]
Hi All,
    I am trying to bringup Ceph container on my kubernetes cluster.
I am facing the issue of OSD is not coming UP and MON-Check pod is continuously throwing the error.
Following is the error I am getting from OSD.

```
2019-04-26 12:12:59  /opt/ceph-container/bin/entrypoint.sh: Creating osd
+/opt/ceph-container/bin/common_functions.sh:12: log(): timestamp='2019-04-26 12:12:59'
+/opt/ceph-container/bin/common_functions.sh:13: log(): echo '2019-04-26 12:12:59  /opt/ceph-container/bin/entrypoint.sh: Creating osd'
+/opt/ceph-container/bin/common_functions.sh:14: log(): return 0
++/opt/ceph-container/bin/osd_directory.sh:14: osd_directory(): uuidgen
+/opt/ceph-container/bin/osd_directory.sh:14: osd_directory(): UUID=9c8ba93e-0441-48c7-b491-c6caeff59cbd
++/opt/ceph-container/bin/osd_directory.sh:15: osd_directory(): ceph-authtool --gen-print-key
+/opt/ceph-container/bin/osd_directory.sh:15: osd_directory(): OSD_SECRET=AQDL9cJc3L53CRAAoykTcZ77MrhR7pdxzS0Ndg==
++/opt/ceph-container/bin/osd_directory.sh:16: osd_directory(): echo '{"cephx_secret": "AQDL9cJc3L53CRAAoykTcZ77MrhR7pdxzS0Ndg=="}'
++/opt/ceph-container/bin/osd_directory.sh:16: osd_directory(): ceph --cluster ceph osd new 9c8ba93e-0441-48c7-b491-c6caeff59cbd -i - -n client.bootstrap-osd -k /var/lib/ceph/bootstrap-osd/ceph.keyring
**unable to parse addrs in 'ceph-mon'
2019-04-26 12:12:59.378 7fee86140700 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 22] error connecting to the cluster
+/opt/ceph-container/bin/osd_directory.sh:16: osd_directory(): OSD_ID='server name not found: ceph-mon (Name or service not known)'**
```
It seems ceph-mon is mentioned as mon-host parameter in ceph.conf file as below
```
osd_pool_default_pg_num = 128
osd_pool_default_pgp_num = 128
osd_pool_default_size = 3
osd_pool_default_min_size = 1

mon_osd_full_ratio = .95
mon_osd_nearfull_ratio = .85

**mon_host = ceph-mon**
```
ceph-mon is a clusterIP service which has the end points of all the Mon IP and Port number

Kubernetes pod should resolve these IP from the service name.
I think, SkyDNS Resolution , we need to mention to resolve this as per the document.
For SkyDNS resolution, i have added following lines on my host machines of resolv.conf file
```
search svc.cluster.local #Your kubernetes cluster ip domain

nameserver 10.233.0.10     #The cluster IP of skyDNS
```
But Still  OSD pod and Mon-check pods are not able to resolve the ceph-mon parameter
Also, I have added the dnspolicy and postStart Lifecycle on osd yaml as below
```
      dnsConfig:
        nameservers:
          - 10.233.0.10
        searches:
          - svc.cluster.local
      containers:
        - name: ceph-mon
          image: ceph/daemon:latest
          imagePullPolicy: Always
          lifecycle:
            postStart:
                exec:
                  command: ["/bin/sh", "-c", "echo ceph-mon.ceph.svc.cluster.local ceph-mon >> /etc/hosts"]
          ports:
            - containerPort: 6789
```

But Still, OSD and Mon-check could not resolve the IP address of Mon-host
Kindly provide your guidance to resolve the monitors IP on  ceph-mon?

Thanks,
Kannan V
