### ISSUE TITLE
【ceph/daemon】CEPH can't cluster failure under docker？

### ISSUE THREAD

**Issue by kervin521** [ceph/ceph-container#1439]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
![image](https://user-images.githubusercontent.com/9798724/61873252-13562780-af18-11e9-85ca-666d36480c11.png)

What you expected to happen:

How to reproduce it (minimal and precise):

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version (e.g. `docker version`):
* Ceph version (e.g. `ceph -v`):

**Comment by kervin521** [comment]
cluster [DBG] mgrmap e1: no daemons active

enable_multiple, ever_enabled_multiple: 0,0


compat: compat={},rocompat={},incompat={1=base v0.20,2=client writeable ranges,3=default file layouts on dirs,4=dir inode in separate object,5=mds uses versioned encoding,6=dirfrag is stored in omap,8=no anchor table,9=file layout v2,10=snaprealm v2}


legacy client fscid: -1


 


No filesystems configured

**Comment by dsavineau** [comment]
Honnestly I don't understand what is the issue.

Could you share your ceph setup (how many mons, mgrs, osds, etc...), the docker and ceph version, the logs (full docker logs) and other stuff that could be useful to understand the issue (docker command, etc..).

```console
cluster [DBG] mgrmap e1: no daemons active
```

Do you have a mgr node running ?

**Comment by kervin521** [comment]
Docker version 18.09.7, build 2d0083d
ceph version 13.2.6 (7b695f835b03642f85998b2ae7b6dd093d9fbce4) mimic (stable)

**Comment by kervin521** [comment]
```yml
version: '3.7'
services:
  mon:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: mon
    command: ceph mon
    network_mode: host
    environment:
      - CEPH_DAEMON=mon
      - NETWORK_AUTO_DETECT=1
      - CEPH_DEVEL=true
      - FLAVORS="nautilus,centos,7"
      - MON_IP=172.21.32.104,172.21.32.106,172.21.32.110
      - CEPH_PUBLIC_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
      - CEPH_CLUSTER_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    deploy:
      replicas: 1
      mode: replicated
      endpoint_mode: dnsrr
      
  mon2:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: mon2
    command: ceph mon
    network_mode: host
    environment:
      - CEPH_DAEMON=mon
      - NETWORK_AUTO_DETECT=1
      - CEPH_DEVEL=true
      - FLAVORS="nautilus,centos,7"
      - MON_IP=172.21.32.104,172.21.32.106,172.21.32.110
      - CEPH_PUBLIC_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
      - CEPH_CLUSTER_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    depends_on:
      - mon
    deploy:
      replicas: 2
      mode: replicated
      endpoint_mode: dnsrr
      
  rgw:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: rgw
    command: ceph rgw
    restart: always
    privileged: true
    network_mode: host
    environment:
      - CEPH_DAEMON=rgw
      - NETWORK_AUTO_DETECT=1
      - CEPH_DEVEL=true
      - FLAVORS="nautilus,centos,7"
      - MON_IP=172.21.32.104,172.21.32.106,172.21.32.110
      - CEPH_PUBLIC_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
      - CEPH_CLUSTER_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    links:
      - mon2
    depends_on:
      - mon
    deploy:
      replicas: 1
      mode: replicated
      endpoint_mode: dnsrr
      
  mds:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: mds
    command: ceph mds
    restart: always
    privileged: true
    network_mode: host
    environment:
      - CEPH_DAEMON=mds
      - NETWORK_AUTO_DETECT=1
      - CEPHFS_CREATE=1
      - CEPH_DEVEL=true
      - FLAVORS="nautilus,centos,7"
      - MON_IP=172.21.32.104,172.21.32.106,172.21.32.110
      - CEPH_PUBLIC_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
      - CEPH_CLUSTER_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    links:
      - mon2
      - rgw
    depends_on:
      - mon
    deploy:
      replicas: 1
      mode: replicated
      endpoint_mode: dnsrr 
      
  osd:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: osd
    command: ceph osd
    restart: always
    privileged: true
    network_mode: host
    environment:
      - CEPH_DAEMON=osd
      - NETWORK_AUTO_DETECT=1
      - CEPH_DEVEL=true
      - FLAVORS="nautilus,centos,7"
      - MON_IP=172.21.32.104,172.21.32.106,172.21.32.110
      - CEPH_PUBLIC_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
      - CEPH_CLUSTER_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
      - CEPH_OSD_POOL_DEFAULT_SIZE=2
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /dev:/dev
      - /opt/ceph/rbd:/var/lib/ceph/osd
      - /var/log/ceph/:/var/log/ceph
    links:
      - mon2
      - rgw
    depends_on:
      - mon
    deploy:
      replicas: 2
      mode: replicated
      endpoint_mode: dnsrr 
      
  mgr:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: mgr
    command: ceph mgr
    restart: always
    privileged: true
    network_mode: host
    environment:
      - CEPH_DAEMON=mgr
      - NETWORK_AUTO_DETECT=1
      - CEPH_DEVEL=true
      - FLAVORS="nautilus,centos,7"
      - MON_IP=172.21.32.104,172.21.32.106,172.21.32.110
      - CEPH_PUBLIC_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
      - CEPH_CLUSTER_NETWORK=172.21.32.0/24,172.18.0.0/16,10.0.0.0/16
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    links:
      - mon2
      - rgw
    depends_on:
      - mon
    deploy:
      replicas: 1
      mode: replicated
      endpoint_mode: dnsrr
 
  mysql:
    image: 172.21.32.31:5000/mysql-canal:5.7.22
    container_name: mysql
    restart: always
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=SqlPwd1@
    volumes:
      - /home/deploy/config/mysql/data:/var/lib/mysql
      - /home/deploy/config/mysql/conf/docker.cnf:/etc/mysql/conf.d/docker.cnf
    ports:
      - 3306:3306
    deploy:
      replicas: 2

  mysql3307:
    image: 172.21.32.31:5000/mysql:5.7.22
    container_name: mysql3307
    restart: always
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=MysqlPwd1@
    volumes:
      - /home/deploy/config/mysql3307/data:/var/lib/mysql
      - /home/deploy/config/mysql3307/conf/docker.cnf:/etc/mysql/conf.d/docker.cnf
    ports:
      - 3307:3306
    deploy:
      replicas: 2

networks:
   hostnet:
      external: true
      name: host
   ingress:
     driver: overlay
     attachable: true
   nonet:
     external: true
     name: none

```

**Comment by dsavineau** [comment]
This is very confusing because there's a lot of contradiction in your configuration.

You said you're using `ceph version 13.2.6` so Mimic but you're using a Luminous (and outdated) container image `ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7`
You also set `FLAVORS="nautilus,centos,7"`, which is only used for building an image so I don't understand what Ceph release you want to use betwee Luminous, Mimic and Nautilus. BTW `CEPH_DEVEL=true` is also only for building container image purpose.

You're configuring `command` for each node but you shouldn't have to do this because the container image will executed the right ceph command based on the `CEPH_DAEMON` env variable (which is also set).

You also use both `NETWORK_AUTO_DETECT` and `MON_IP`/`CEPH_PUBLIC_NETWORK`/`CEPH_CLUSTER_NETWORK` in the same time which are exclusive.
Finally `MON_IP`/`CEPH_PUBLIC_NETWORK`/`CEPH_CLUSTER_NETWORK` doesn't support multiple values. `MON_IP` only needs to be set on mon nodes which a single IP address value. `CEPH_PUBLIC_NETWORK`/`CEPH_CLUSTER_NETWORK` are using a single network cidr.

**Comment by kervin521** [comment]
```
version: '3.7'
services:
  mon:
    image: ceph/daemon:latest-nautilus-devel
    container_name: mon
    environment:
      - CEPH_DAEMON=mon
      - MON_IP=0.0.0.0
      - CEPH_PUBLIC_NETWORK=172.21.32.0/24
      - CEPH_CLUSTER_NETWORK=172.21.32.0/24
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    deploy:
      replicas: 2
    networks:
      - hostnet
      
  rgw:
    image: ceph/daemon:latest-nautilus-devel
    container_name: rgw
    restart: always
    environment:
      - CEPH_DAEMON=rgw
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    deploy:
      replicas: 2
    networks:
      - hostnet 
      
  osd:
    image: ceph/daemon:latest-nautilus-devel
    container_name: osd
    restart: always
    privileged: true
    environment:
      - CEPH_DAEMON=osd
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /dev:/dev
      - /opt/ceph/rbd:/var/lib/ceph/osd
      - /var/log/ceph/:/var/log/ceph
    deploy:
      replicas: 2
    networks:
      - hostnet 
      
  mgr:
    image: ceph/daemon:latest-nautilus-devel
    container_name: mgr
    restart: always
    environment:
      - CEPH_DAEMON=mgr
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    deploy:
      replicas: 2
    networks:
      - hostnet 

networks:
   hostnet:
      external: true
      name: host
   ingress:
     driver: overlay
     attachable: true
   nonet:
     external: true
     name: none

```
According to what you said, I can't configure the cluster successfully under swarm. How should I configure it?
