### ISSUE TITLE
rbd: failed to load rbd kernel module

### ISSUE THREAD

**Issue by kervin521** [ceph/ceph-container#1449]
Is this a bug report or feature request?
* Bug Report
```
[root@dbs-server11 /]# ceph -s
  cluster:
    id:     a5c4503c-f524-4a60-9fad-0ac2954b6240
    health: HEALTH_OK

  services:
    mon: 1 daemons, quorum dbs-server11 (age 15m)
    mgr: dbs-server11(active, since 2h)
    osd: 1 osds: 1 up (since 16m), 1 in (since 2h)

  data:
    pools:   1 pools, 128 pgs
    objects: 6 objects, 35 B
    usage:   1.0 GiB used, 9.0 GiB / 10 GiB avail
    pgs:     128 active+clean

  io:
    client:   14 KiB/s rd, 16 op/s rd, 0 op/s wr

[root@dbs-server11 /]# ceph -v
ceph version 14.2.2-296-g6f82bc1 (6f82bc122c6e64d8c6bf9b9428a4b22d11f63f3e) nautilus (stable)
[root@dbs-server11 /]# rbd info data2
rbd image 'data2':
        size 16 GiB in 4096 objects
        order 22 (4 MiB objects)
        snapshot_count: 0
        id: 37336b8b4567
        block_name_prefix: rbd_data.37336b8b4567
        format: 2
        features: layering
        op_features:
        flags:
        create_timestamp: Wed Aug  7 09:53:20 2019
        access_timestamp: Wed Aug  7 09:53:20 2019
        modify_timestamp: Wed Aug  7 09:53:20 2019
[root@dbs-server11 /]# rbd map data2
modinfo: ERROR: Module alias rbd not found.
rbd: failed to load rbd kernel module (1)
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory
[root@dbs-server11 /]#
```
**Bug Report**

What happened:

What you expected to happen:

How to reproduce it (minimal and precise):

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version (e.g. `docker version`):
* Ceph version (e.g. `ceph -v`):
