### ISSUE TITLE
dashboard in demo mode?

### ISSUE THREAD

**Issue by shane-axiom** [ceph/ceph-container#1755]
Hi all, is the [ceph dashboard](https://docs.ceph.com/en/latest/mgr/dashboard/) available in demo mode? I can't seem to enable it, and have tried with the following images:

* ceph/daemon:latest
* ceph/daemon:v5.0.3-stable-5.0-octopus-centos-8
* ceph/daemon:v4.0.14-stable-4.0-nautilus-centos-7

Docker command:

```
docker run --rm --name ceph-demo \
  -e CEPH_DEMO_UID=qqq \
  -e CEPH_DEMO_ACCESS_KEY=qqq \
  -e CEPH_DEMO_SECRET_KEY=qqq \
  -e CEPH_DEMO_BUCKET=qqq \
  -e NETWORK_AUTO_DETECT=4 \
  ceph/daemon:$TAG demo
```

By default, these are the enabled mgr modules:

```
$ docker exec ceph-demo ceph mgr module ls | jq '.enabled_modules' 
[
  "iostat",
  "restful"
]
```

and this is the output of `ceph -s`

```
✗ docker exec ceph-demo ceph -s
  cluster:
    id:     3b4a17b8-5d6d-4550-8d00-09fadface282
    health: HEALTH_WARN
            mon 84263c2f7892 is low on available space
 
  services:
    mon: 1 daemons, quorum 84263c2f7892 (age 99s)
    mgr: 84263c2f7892(active, since 95s)
    mds: cephfs:1 {0=demo=up:active}
    osd: 1 osds: 1 up (since 94s), 1 in (since 94s)
    rgw: 1 daemon active (84263c2f7892)
 
  task status:
    scrub status:
        mds.demo: idle
 
  data:
    pools:   9 pools, 227 pgs
    objects: 228 objects, 8.8 KiB
    usage:   1.0 GiB used, 99 GiB / 100 GiB avail
    pgs:     227 active+clean
 
  progress:
    PG autoscaler decreasing pool 9 PGs from 32 to 8 (0s)
      [............................] 
    PG autoscaler decreasing pool 8 PGs from 32 to 8 (1s)
      [............................] 

```

If I wait until the cluster is fully initialized and then run this

```
docker exec ceph-demo ceph mgr module enable dashboard
```

The container dies immediately

```
teardown: managing teardown after SIGCHLD
teardown: Sending SIGTERM to PID 2429
teardown: Waiting PID 2429 to terminate ./opt/ceph-container/bin/docker_exec.sh: line 32: warning: run_pending_traps: bad value in trap_list[17]: 0x55a5f2ae07b0
/opt/ceph-container/bin/docker_exec.sh: line 32: warning: run_pending_traps: bad value in trap_list[17]: 0x55a5f2ae07b0

teardown: Process 2429 is terminated
teardown: Bye Bye, container will die with return code 0
```

If I run `docker exec ceph-demo ceph mgr module enable dashboard` while the cluster is still initializing, I can get `dashboard` to show up in the enabled modules:

```
docker exec ceph-demo ceph mgr module ls | jq '.enabled_modules'
[
  "dashboard",
  "iostat",
  "restful"
]
```

However there's still nothing listening on port 8443:

```
docker exec ceph-demo yum -y install net-tools
...
docker exec ceph-demo netstat -tulpn4         
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.17.0.5:6802         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6803         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6804         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6805         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6806         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6807         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6808         0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:36505           0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6809         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6810         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6811         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:3300         0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      1962/python3        
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6800         0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.17.0.5:6801         0.0.0.0:*               LISTEN      -                   
udp        0      0 0.0.0.0:111             0.0.0.0:*                           -                   
udp        0      0 127.0.0.1:969           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:56102           0.0.0.0:*                           -   
```

8080 appears to be an s3 compat endpoint

```
curl -sS "http://172.17.0.5:8080" 
<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>anonymous</ID><DisplayName></DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>%
```
