### ISSUE TITLE
cephadm has failed ContainerInspectInfo

### ISSUE THREAD

**Issue by httaotao** [ceph/ceph-container#2155]
Hi, these days I have been installed ceph(reef) in one node without network. So I use rpm to install and download docker iamge in this node.  But I don't know how to use cephadm bootstrap to init. When I use ``` skip-pull ```, there has Error in ceph status. I don't know how to fix it. 

```
# docker image ls
REPOSITORY          TAG       IMAGE ID       CREATED      SIZE
quay.io/ceph/ceph   v18       8033e460cc3a   9 days ago   1.25GB

```

Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

ceph status has error:

```
# ceph status
  cluster:
    id:     96818c10-504c-11ee-b9d6-005056a0cc54
    health: HEALTH_ERR
            Module 'cephadm' has failed: ContainerInspectInfo(image_id='8033e460cc3a60c2c8f7cfda7e89e1738b13578d0b277128c178cced26b7cb10', ceph_version='ceph version 18.2.0 (5dd24139a1eada541a3bc16b6941c5dde975e26d) reef (stable)', repo_digests=[''])
            OSD count 0 < osd_pool_default_size 2

  services:
    mon: 1 daemons, quorum master (age 69m)
    mgr: master.hpmxfg(active, since 69m)
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:

```

How to reproduce it (minimal and precise):

1). install ceph 
2). use common ```  cephadm bootstrap --mon-ip  xxx  --single-host-defaults  --cluster-network  xxx    --skip-pull ```
3). ceph status 

**Environment**:
* OS (e.g. from /etc/os-release):   CentOS Linux release 8.5.2111
* Kernel (e.g. `uname -a`): Linux master 4.18.0-348.el8.x86_64
* Docker version (e.g. `docker version`): Docker version 24.0.6, build ed223bc
* Ceph version (e.g. `ceph -v`): ceph version 18.2.0 (5dd24139a1eada541a3bc16b6941c5dde975e26d) reef (stable)
