### ISSUE TITLE
OSD not work

### ISSUE THREAD

**Issue by flemzord** [ceph/ceph-container#648]
Hello,
I have unimmer with Kubernetes 1.6.2 + CoreOS + Ceph.
Here are the configurations of Kubernetes

# configuration kube
````
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: ceph-osd
  namespace: ceph
  labels:
    app: ceph
    daemon: osd
spec:
  template:
    metadata:
      labels:
        app: ceph
        daemon: osd
    spec:
      nodeSelector:
        storage: "true"
      volumes:
        - name: devices
          hostPath:
            path: /dev
        - name: ceph
          hostPath:
            path: /opt/ceph
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
      containers:
        - name: osd-pod
          image: ceph/daemon:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: devices
              mountPath: /dev
            - name: ceph
              mountPath: /var/lib/ceph
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
          securityContext:
            privileged: true
          env:
            - name: CEPH_DAEMON
              value: OSD
            - name: OSD_DEVICE
              value: $CEPH_DISK_DEVICE$
            - name: KV_TYPE
              value: k8s
            - name: CLUSTER
              value: ceph
            - name: CEPH_GET_ADMIN_KEY
              value: "1"
          livenessProbe:
              tcpSocket:
                port: 6800
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 6800
              timeoutSeconds: 5
````
# logs pod
````
kubectl logs -n ceph po/ceph-osd-djpk5                                              

2017-05-17 08:48:29  /entrypoint.sh: k8s: config is stored as k8s secrets.
2017-05-17 08:48:29  /entrypoint.sh: k8s: does not generate the admin key. Use Kubernetes secrets instead.
2017-05-17 08:48:29  /entrypoint.sh: Device detected, assuming ceph-disk scenario is desired
2017-05-17 08:48:29  /entrypoint.sh: Preparing and activating /dev/vdb
````
