### ISSUE TITLE
ceph health warning with "no active mgr" on using yamls from kubernetes example

### ISSUE THREAD

**Issue by sudhirpandey** [ceph/ceph-container#844]
I have been playing around with k8s based ceph deployment on set of nodes
so far, i have managed to deploy cep-mons via ceph-mon-v1-dp.yaml, making hostNewtork true.
ceph-osds , via ceph-osd-prepare-v1-ds.yaml and ceph-osd-activate-v1-ds.yaml
with hostNewtork true, so that my pods have access to host interfaces to use two newtorks for public and private plane.
Mds is deployed as normal pod(non privilaged)

but my ceph status is not healthy still and it missing some other stats on ceph -s
``` cluster:
    id:     6b821319-4cf0-4849-acf9-529916b7c75e
    health: HEALTH_WARN
            no active mgr

  services:
    mon: 3 daemons, quorum mon1xxx, mon1xxx, mon3xxx
    mgr: no daemons active
    mds: cephfs-1/1/1 up  {0=ceph-mds-4000341329-jvfw5=up:active}
    osd: 3 osds: 3 up, 3 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 bytes
    usage:   0 kB used, 0 kB / 0 kB avail
    pgs: 
```

following this link http://docs.ceph.com/docs/master/mgr/,  i see this 

```
Since the 12.x (luminous) Ceph release, the ceph-mgr daemon is required for normal operations
```
so i am wondering if we are missing a yaml for mgr daemon in atleast luminous to get it started. I have no idea if is also the problem for nothing being shown up in data /usage section too.

Can you shed some light on how to move forward with the setup.
The ceph version deployed is
```
oc exec ceph-mon-2119246816-4xqn0 -- ceph --version
ceph version 12.2.1 (3e7492b9ada8bdc9a5cd0feafd42fbca27f9c38e) luminous (stable)
```

**Comment by sudhirpandey** [comment]
Update i was able to get it running by adding the cephmrg deployment , looking at helm templates in ceph-helm and needed to make filewall openings same as  for cephosods, thats why i ran it on same node as ceph osd by using nodeselector , but i am not sure if its okey  to run in same node as ceph osd.? any suggestions

also needed to create bootstarp key for mgr and have it as k8s secret

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ceph
    daemon: mgr
  name: ceph-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph
      daemon: mgr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/affinity: |
          {
            "podAntiAffinity": {
              "RequiredDuringSchedulingIgnoredDuringExecution": [{
                "labelSelector": {
                  "matchExpressions": [{
                    "key": "daemon",
                    "operator": "In",
                    "values":["mon"]
                  }]
                },
              "topologyKey": "kubernetes.io/hostname"
              }]
            }
          }
      labels:
        app: ceph
        daemon: mgr
      name: ceph-mgr
      namespace: ceph
    spec:
      containers:
      - command:
        - /scripts/resolvfix.sh
        env:
        - name: CEPH_DAEMON
          value: MGR
        - name: KV_TYPE
          value: k8s
        - name: NETWORK_AUTO_DETECT
          value: "4"
        - name: CLUSTER
          value: ceph
        image: ceph/daemon:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - bash
            - /check_mgr.sh
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: ceph-mgr
        readinessProbe:
          exec:
            command:
            - bash
            - /check_mgr.sh
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 100Mi
          requests:
            cpu: "1"
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/ceph
          name: ceph-conf
        - mountPath: /var/lib/ceph/bootstrap-mgr
          name: ceph-bootstrap-mgr-keyring
        - mountPath: /scripts
          name: resolvefix
        - mountPath: /check_mgr.sh
          name: checkmgr
          subPath: check_mgr.sh
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        cephosd: enable
      restartPolicy: Always
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ceph-conf
        secret:
          defaultMode: 420
          secretName: ceph-conf-combined
      - name: ceph-bootstrap-mgr-keyring
        secret:
          defaultMode: 420
          secretName: ceph-bootstrap-mgr-keyring
      - configMap:
          defaultMode: 0744
          name: resolvescript
        name: resolvefix
      - configMap:
          defaultMode: 0744
          name: checkmgr
        name: checkmgr

```
checkmgr is borrowed script from ceph-helm

```
apiVersion: v1
data:
  check_mgr.sh: |2
    #!/bin/bash
    set -ex
    export LC_ALL=C
    IS_MGR_AVAIL=`ceph mgr dump | python -c "import json, sys; print json.load(sys.stdin)['available']"`
    if [ "${IS_MGR_AVAIL}" = True ]; then
      exit 0
    else
      exit 1
    fi
kind: ConfigMap
metadata:
  name: checkmgr
```
and resolvfix is just the wrapperscript to fix pods resolv.conf file before executing the entry point as in kube 1.5.2 we dont have have clusterFirst dns policy in pods with host networking.

```
apiVersion: v1
data:
  resolvfix.sh: |
    #!/bin/bash
    interface=$(grep -vE "lo:|face|Inter" /proc/net/dev | sort -n -k 2 | tail -1 | awk '{ sub (":", "", $1); print $1 }')
    ipaddr=$(ip -4 -o a s $interface | grep "scope global" | awk '{ sub ("/..", "", $4); print $4 }')
    cat > /etc/resolv.conf << EOF
    search ceph.svc.cluster.local
    nameserver $ipaddr
    EOF

    exec /entrypoint.sh
kind: ConfigMap
metadata:
  name: resolvescript
```
